services:
  mysql:
    image: mysql:8.0
    container_name: dwa_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: oltp_amazon
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]

volumes:
  mysql_data: